name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
   # - name: Build with Gradle
   #   run: ./gradlew assembleRelease
 
    - name : Retrieve Version
      run: |
       echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
      id: android_version
    
    - name: Get version
      run: |
        echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
 
    - run: |
          gh release create ${{process.env.version_name}} release.tar.xz
      env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
      name: Creates a release in GitHub and uploads attachments
